import Head from "next/head";

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Content from "@/components/Content";
import ConvertOptions from "@/components/ConvertOptions";
import Convert from "@/components/Convert";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Content>
          <Hero />
          <Convert />
        </Content>
      </main>
    </>
  );
}
